version: '3.3'

networks:
  swarm_overlay:
    external:
      name: traefik-net

configs:
  traefik.toml:
    file: ./configs/traefik.toml

services:
  traefik:
    image: traefik
    command: --docker --docker.swarmmode --docker.domain=${DOMAIN} --docker.watch --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    # docker in docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # if not using docker configs
      #- /data/traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 8080:8080
    networks:
      - swarm_overlay
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
